timeout: 10

wallpaper: boot():/wallpaper.jpg
MARGIN_GRADIENT: 0
interface_resolution: 1280x720
interface_branding_colour: 1
interface_branding: Bleed Kernel - by Myles "Mellurboo" Wilson

interface_help_colour: 1
editor_validation: no

/Bleed-Kernel
    protocol: limine
    path: boot():/boot/bleed-kernel
    MODULE_PATH=boot():/boot//initrd.tar
    COMMENT: Standard Bleed Kernel Boot